apiVersion: apps/v1
kind: Deployment
metadata:
  name: smrpo-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smrpo-backend
  template:
    metadata:
      labels:
        app: smrpo-backend
    spec:
      containers:
        - image: amihevc/smrpo-backend
          name: smrpo-backend
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-smrpo-backend
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-smrpo-backend
                  key: password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-smrpo-backend
                  key: database
            - name: POSTGRES_HOST
              valueFrom:
                secretKeyRef:
                  name: db-smrpo-backend
                  key: hostname
          ports:
            - containerPort: 8003
              name: server
              protocol: TCP
---

apiVersion: v1
kind: Service
metadata:
  name: smrpo-backend
spec:
  type: LoadBalancer
  ports:
    - port: 8003
      protocol: TCP
      targetPort: server
  selector:
    app: smrpo-backend