name: Docker Build Images

on:
  workflow_dispatch:
  push:
    branches:
      - main
    pull-request:
      -main

env:
  IMAGE_NAME: 'amihevc/smrpo-backend'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-qemu-action@v2

      - uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Get current time
        id: current-time
        uses: josStorer/get-current-time@v2.0.2
        with:
          format: YYYY-MM-DD-HH-mm-ss
          utcOffset: "+02:00"

      - name: Build and push with date and latest
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/smrpo-backend:${{ steps.current-time.outputs.formattedTime }} , ${{ secrets.DOCKERHUB_USERNAME }}/smrpo-backend:latest